coverage_service: xml
xcodeproj: tmdb-movies.xcodeproj
workspace: tmdb-movies.xcworkspace
scheme: DEV
input_format: profdata
source_directory: tmdb-movies/
output_directory: test_output/
ignore:
  - Pods/*
