os: osx
osx_image: xcode10.2
env:
  matrix:
    secure: EFFfRUH588M/oSXvvkk5WDKBSrkuSrtHty7WeaPWnWnlMY3oMw9Dpb7ZFM+0Ka/N2j1RxOKtGJtDI6ZPAkZg06uYcrc351l122s7WNhXWAsl2ookghzPQNUtqUE7m4Ao/yAsJzRyvV4XBwaJp0ki0t+Ydp9arj9y4G/MgwlMk+wPv8xkbjCdE3QejfsGFoW+1qWb3lQ/+SuG1NMP2wCOXrvAnQ0LmGbci1t/Vdx8Z+bdqHZv5RR8wQmjL6IWGyNAuFxMy8txRL0CzddGHnFlo+XnjDI5SBKIGD2fWGU3SUPYG9UjDPnRPeXISwlFrvwuzn5+5j5BDzsOqbF+veTJqShD1I3khuBg6rEQ/rP+mVXNW2hnL4TcAENoY/q2IsbyYH+tCPMw+o1cXtv9PzMRiqVYvm6+H436Fxbyg9OMtljN5c513PsodOwuRgZd3UHuWWkvIpgaaS7Vs66YrPYtmjW4MbQGDlIAvZ/TW15o5aHLkFqLYRopOJBjSC8UjSuUxKmjS3LAbYPoKRh4KyLbd1JL8lwuY0KUfnnZR/cZmHuz/JFzDt10qfc/asjs+CflkMcQR+Orb/mEQ1BEFel/f7REr/0T2xOj+no1QSWDzQUoGkeOuCOPXEPGTTQeFb2CiEmv1AkREOWvfHbQ9fLtZvms28IaDWMhzl18+ElVUw4=
before_install:
- gem install bundler:2.0.1
install:
- bundle install
- bundle exec pod keys set "TMDbMoviesAPIKey" $TMDBMOVIESAPIKEY
- bundle exec pod install --repo-update
script:
- bundle exec fastlane test
