os: osx
osx_image: xcode10.2
branches:
  only:
    - development
before_install:
- gem install bundler:2.0.1
- bundle install
- bundle exec pod install --no-repo-update
script:
  - bundle exec fastlane test
